In [16]:
import kNN

In [17]:
data_set, labels = kNN.createDataSet()

In [18]:
print(data_set)
print(labels)

[[ 1.   1.1]
 [ 1.   1. ]
 [ 0.   0. ]
 [ 0.   0.1]]
['A', 'A', 'B', 'B']


In [19]:
kNN.classify0([0.8, 0.8], data_set, labels, 3)

AttributeError: 'dict' object has no attribute 'iteritems'

In [20]:
d = {'a':10, 'b': 'hello', 'd': 20}; d

{'a': 10, 'b': 'hello', 'd': 20}

In [21]:
d.get('a')

10

In [22]:
import numpy as np

In [23]:
"This is a test string from Andrew".split()

['This', 'is', 'a', 'test', 'string', 'from', 'Andrew']

In [24]:
x = [20, 13, 7, 33, 24]

In [25]:
inX = [0.8, 0.8]

In [26]:
data_set_size = data_set.shape[0]; data_set_size

4

In [6]:
import importlib 

In [7]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA\\Ch02\\kNN.py'>

In [ ]:
kNN.classify0([0.8, 0.8], data)

In [ ]:
# diff_mat = np.tile(inX, (data_set_size))
diff_mat = inX - data_set; diff_mat

# datingdataset

In [27]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA\\Ch02\\kNN.py'>

In [32]:
datingDataMat, datingLabels = kNN.file2matrix('datingTestSet2.txt')

In [29]:
datingDataMat[:10]

array([[  4.09200000e+04,   8.32697600e+00,   9.53952000e-01],
       [  1.44880000e+04,   7.15346900e+00,   1.67390400e+00],
       [  2.60520000e+04,   1.44187100e+00,   8.05124000e-01],
       [  7.51360000e+04,   1.31473940e+01,   4.28964000e-01],
       [  3.83440000e+04,   1.66978800e+00,   1.34296000e-01],
       [  7.29930000e+04,   1.01417400e+01,   1.03295500e+00],
       [  3.59480000e+04,   6.83079200e+00,   1.21319200e+00],
       [  4.26660000e+04,   1.32763690e+01,   5.43880000e-01],
       [  6.74970000e+04,   8.63157700e+00,   7.49278000e-01],
       [  3.54830000e+04,   1.22731690e+01,   1.50805300e+00]])

In [30]:
datingLabels[:10]

[3, 2, 1, 1, 1, 1, 3, 3, 1, 3]

# Noralization 정규화 

In [33]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA\\Ch02\\kNN.py'>

In [36]:
datingDataMat, datingLabels = kNN.file2matrix('datingTestSet2.txt')

In [37]:
normMat, ranges, minVals = kNN.autoNorm(datingDataMat)

In [38]:
print(normMat)
print(ranges)
print(minVals)

[[ 0.44832535  0.39805139  0.56233353]
 [ 0.15873259  0.34195467  0.98724416]
 [ 0.28542943  0.06892523  0.47449629]
 ..., 
 [ 0.29115949  0.50910294  0.51079493]
 [ 0.52711097  0.43665451  0.4290048 ]
 [ 0.47940793  0.3768091   0.78571804]]
[  9.12730000e+04   2.09193490e+01   1.69436100e+00]
[ 0.        0.        0.001156]


# TEST

In [45]:
importlib.reload(kNN)

<module 'kNN' from 'C:\\pydev\\MLiA\\Ch02\\kNN.py'>

In [46]:
kNN.datingClassTest()

the classifier came back with: 3, the real answer is: 3
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 3, the real answer is: 3
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 2, the real answer is: 2
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answer is: 1
the classifier came back with: 1, the real answe