In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [7]:
cd ch04

[Error 2] : u'ch04'
C:\pydev\machinelearninginaction\Ch04


In [8]:
pwd

u'C:\\pydev\\machinelearninginaction\\Ch04'

In [9]:
import bayes

In [10]:
reload(bayes)

<module 'bayes' from 'bayes.pyc'>

In [11]:
list_of_post, class_label = bayes.loadDataSet()
list_of_post
class_label

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

[0, 1, 0, 1, 0, 1]

In [12]:
my_vocab_list = bayes.createVocabList_lec(list_of_post)

document: ['my', 'dog', 'has', 'flea', 'problems', 'help', 'please']
document: set(['help', 'please', 'problems', 'dog', 'flea', 'has', 'my'])
document: ['my', 'dog', 'has', 'flea', 'problems', 'help', 'please']
document: ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']
document: set(['maybe', 'park', 'dog', 'to', 'stupid', 'take', 'not', 'him'])
document: ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']
document: ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']
document: set(['cute', 'love', 'I', 'is', 'dalmation', 'so', 'my', 'him'])
document: ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him']
document: ['stop', 'posting', 'stupid', 'worthless', 'garbage']
document: set(['worthless', 'stupid', 'stop', 'posting', 'garbage'])
document: ['stop', 'posting', 'stupid', 'worthless', 'garbage']
document: ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him']
document: set(['licks', 'to', 'stop', 'how', 'ate', 'mr', 'steak', 'my', 'hi

In [14]:
len(my_vocab_list)

32

In [15]:
reload(bayes)

<module 'bayes' from 'bayes.py'>

In [17]:
list_of_post[0]
bayes.setOfWords2Vec_lec(my_vocab_list, list_of_post[0])

['my', 'dog', 'has', 'flea', 'problems', 'help', 'please']

returnVec: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word: my
vocabList: ['cute', 'love', 'help', 'garbage', 'quit', 'I', 'problems', 'is', 'park', 'stop', 'flea', 'dalmation', 'licks', 'food', 'not', 'him', 'buying', 'posting', 'has', 'worthless', 'ate', 'to', 'maybe', 'please', 'dog', 'how', 'stupid', 'so', 'take', 'mr', 'steak', 'my']

----->word: my
----->vocablist.index(word): 31
----->returnVec[vocabList.index(word)]: 0
----->returnvec[vocabList.index(word)]: 0
word: dog
vocabList: ['cute', 'love', 'help', 'garbage', 'quit', 'I', 'problems', 'is', 'park', 'stop', 'flea', 'dalmation', 'licks', 'food', 'not', 'him', 'buying', 'posting', 'has', 'worthless', 'ate', 'to', 'maybe', 'please', 'dog', 'how', 'stupid', 'so', 'take', 'mr', 'steak', 'my']

----->word: dog
----->vocablist.index(word): 24
----->returnVec[vocabList.index(word)]: 0
----->returnvec[vocabList.index(word)]: 0
word: has
vocabList: ['cute', 'love', 'help', 'garba

[0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [18]:
list_of_post[1]

['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid']

In [23]:
reload(bayes)

<module 'bayes' from 'bayes.py'>

In [25]:
bayes.setOfWords2Vec(my_vocab_list, list_of_post[1])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0]

In [26]:
reload(bayes)

<module 'bayes' from 'bayes.pyc'>

testingNB

In [27]:
list_of_post, class_label = bayes.loadDataSet()

In [28]:
my_vocab_list = bayes.createVocabList(list_of_post)

In [30]:
trainMat = []
for post in list_of_post:
    trainMat.append(bayes.setOfWords2Vec(my_vocab_list,  post))

In [36]:
trainMat[0:2][:10]

[[0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0]]

In [34]:
trainMat2 = [bayes.setOfWords2Vec(my_vocab_list, post) for ost in list_of_post]

In [35]:
trainMat == trainMat2

False

In [37]:
print(trainMat[0])
print(trainMat[1])

[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0]


In [59]:
reload(bayes)

<module 'bayes' from 'bayes.py'>

In [60]:
bayes.trainNB0_lec(trainMat, class_label)

porb. of abusive: 0.5

-->i: 0
-->if trainCategory[0] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[0]
----> p0Num: [ 1.  1.  2.  1.  1.  1.  2.  1.  1.  1.  2.  1.  1.  1.  1.  1.  1.  1.
  2.  1.  1.  1.  1.  2.  2.  1.  1.  1.  1.  1.  1.  2.]
----> p0Denom: 9.0

-->i: 1
-->if trainCategory[1] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[1]
----> p1Num: [ 1.  1.  1.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.  1.  2.  2.  1.  1.
  1.  1.  1.  2.  2.  1.  2.  1.  2.  1.  2.  1.  1.  1.]
----> p1Denom: 10.0

-->i: 2
-->if trainCategory[2] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[2]
----> p0Num: [ 2.  2.  2.  1.  1.  2.  2.  2.  1.  1.  2.  2.  1.  1.  1.  2.  1.  1.
  2.  1.  1.  1.  1.  2.  2.  1.  1.  2.  1.  1.  1.  3.]
----> p0Denom: 17.0

-->i: 3
-->if trainCategory[3] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[3]
----> p1Num: [ 1.  1.  1.  2.  1.  1.  1.  1.  2.  2.  1.  1.  1.  1.  2.  2.  1.  2.
  1.  2.  1.  2.  2. 

(array([-2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -2.15948425, -3.25809654, -3.25809654, -2.56494936, -3.25809654,
        -2.56494936, -2.56494936, -3.25809654, -2.56494936, -2.56494936,
        -2.56494936, -3.25809654, -2.56494936, -3.25809654, -2.56494936,
        -2.56494936, -1.87180218]),
 array([-3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -2.35137526, -2.35137526, -2.35137526, -3.04452244, -1.94591015,
        -3.04452244, -2.35137526, -2.35137526, -3.04452244, -1.94591015,
        -3.04452244, -1.65822808, -3.04452244, -2.35137526, -3.04452244,
        -3.04452244, -3.04452244]),
 0.5)

In [62]:
my_vocab_list

['cute',
 'love',
 'help',
 'garbage',
 'quit',
 'I',
 'problems',
 'is',
 'park',
 'stop',
 'flea',
 'dalmation',
 'licks',
 'food',
 'not',
 'him',
 'buying',
 'posting',
 'has',
 'worthless',
 'ate',
 'to',
 'maybe',
 'please',
 'dog',
 'how',
 'stupid',
 'so',
 'take',
 'mr',
 'steak',
 'my']

In [63]:
bayes.trainNB0_lec(trainMat, class_label)

porb. of abusive: 0.5

-->i: 0
-->if trainCategory[0] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[0]
----> p0Num: [ 1.  1.  2.  1.  1.  1.  2.  1.  1.  1.  2.  1.  1.  1.  1.  1.  1.  1.
  2.  1.  1.  1.  1.  2.  2.  1.  1.  1.  1.  1.  1.  2.]
----> p0Denom: 9.0

-->i: 1
-->if trainCategory[1] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[1]
----> p1Num: [ 1.  1.  1.  1.  1.  1.  1.  1.  2.  1.  1.  1.  1.  1.  2.  2.  1.  1.
  1.  1.  1.  2.  2.  1.  2.  1.  2.  1.  2.  1.  1.  1.]
----> p1Denom: 10.0

-->i: 2
-->if trainCategory[2] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[2]
----> p0Num: [ 2.  2.  2.  1.  1.  2.  2.  2.  1.  1.  2.  2.  1.  1.  1.  2.  1.  1.
  2.  1.  1.  1.  1.  2.  2.  1.  1.  2.  1.  1.  1.  3.]
----> p0Denom: 17.0

-->i: 3
-->if trainCategory[3] == 1
-->trainCategory: [0, 1, 0, 1, 0, 1]
----> trainMatrix[3]
----> p1Num: [ 1.  1.  1.  2.  1.  1.  1.  1.  2.  2.  1.  1.  1.  1.  2.  2.  1.  2.
  1.  2.  1.  2.  2. 

(array([-2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -2.15948425, -3.25809654, -3.25809654, -2.56494936, -3.25809654,
        -2.56494936, -2.56494936, -3.25809654, -2.56494936, -2.56494936,
        -2.56494936, -3.25809654, -2.56494936, -3.25809654, -2.56494936,
        -2.56494936, -1.87180218]),
 array([-3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
        -2.35137526, -2.35137526, -2.35137526, -3.04452244, -1.94591015,
        -3.04452244, -2.35137526, -2.35137526, -3.04452244, -1.94591015,
        -3.04452244, -1.65822808, -3.04452244, -2.35137526, -3.04452244,
        -3.04452244, -3.04452244]),
 0.5)

In [88]:
reload(bayes)

<module 'bayes' from 'bayes.py'>

In [89]:
p0v, p1v, pAbusive = bayes.trainNB0(trainMat, class_label)

porb. of abusive: 0.5


In [90]:
testEntry = ['loe', 'my', 'dalmeation']

In [91]:
testVec = bayes.setOfWords2Vec(my_vocab_list, testEntry)
testVec

the word: loe is not in my Vocabulary!
the word: dalmeation is not in my Vocabulary!


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [92]:
bayes.classifyNB_lec(testVec, p0v, p1v, pAbusive)

vec2Classify: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
p1Vec: [-3.04452244 -3.04452244 -3.04452244 -2.35137526 -2.35137526 -3.04452244
 -3.04452244 -3.04452244 -2.35137526 -2.35137526 -3.04452244 -3.04452244
 -3.04452244 -2.35137526 -2.35137526 -2.35137526 -2.35137526 -2.35137526
 -3.04452244 -1.94591015 -3.04452244 -2.35137526 -2.35137526 -3.04452244
 -1.94591015 -3.04452244 -1.65822808 -3.04452244 -2.35137526 -3.04452244
 -3.04452244 -3.04452244]
p0Vec: [-2.56494936 -2.56494936 -2.56494936 -3.25809654 -3.25809654 -2.56494936
 -2.56494936 -2.56494936 -3.25809654 -2.56494936 -2.56494936 -2.56494936
 -2.56494936 -3.25809654 -3.25809654 -2.15948425 -3.25809654 -3.25809654
 -2.56494936 -3.25809654 -2.56494936 -2.56494936 -3.25809654 -2.56494936
 -2.56494936 -2.56494936 -3.25809654 -2.56494936 -3.25809654 -2.56494936
 -2.56494936 -1.87180218]
pClass1: 0.5
p1: -3.73766961828, p0: -2.56494935746


0

In [93]:
bayes.testingNB

<function bayes.testingNB>

In [94]:
bayes.testingNB()

porb. of abusive: 0.5
['love', 'my', 'dalmation'] classified as:  0
['stupid', 'garbage'] classified as:  1


In [95]:
testEntry = ['I', 'dumped', 'garbage','for', 'my', 'cute', 'dog']

In [96]:
textVec = bayes.setOfWords2Vec(my_vocab_list, testEntry)
print testVec

the word: dumped is not in my Vocabulary!
the word: for is not in my Vocabulary!
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [98]:
bayes.classifyNB(trainMat, p0v, p1v, pAbusive)

1

In [99]:
t1 = ['a', 'bc', 'def']; t2 = [1, 2, 'hello']

In [100]:
t_a = []; t_e = []

In [102]:
t = []
t.append(t1)

In [103]:
t

[['a', 'bc', 'def']]

In [104]:
t.append(t2); t

[['a', 'bc', 'def'], [1, 2, 'hello']]

In [105]:
tt = []
tt.extend(t1); tt

['a', 'bc', 'def']

In [106]:
tt.extend(t2); tt

['a', 'bc', 'def', 1, 2, 'hello']

In [108]:
reload(bayes)

<module 'bayes' from 'bayes.pyc'>

In [109]:
bayes.spamTest()

porb. of abusive: 0.525
classification error ['yeah', 'ready', 'may', 'not', 'here', 'because', 'jar', 'jar', 'has', 'plane', 'tickets', 'germany', 'for']
the error rate is:  0.1


In [110]:
import numpy as np

In [111]:
randIndex = int(np.random.uniform(0, 50))
randIndex

10

In [114]:
[int(np.random.uniform(0, 50)) for _ in range(10)]
# 중복값이 나온다. 
# 원래는 다른 값이었어도 소숫점을 버리니까

[49, 39, 11, 26, 7, 47, 31, 22, 37, 20]

In [115]:
reload(bayes)

<module 'bayes' from 'bayes.py'>

In [116]:
bayes.spamTest()

porb. of abusive: 0.475
p0V: []
p1V:{}
pSpam
classification error ['scifinance', 'now', 'automatically', 'generates', 'gpu', 'enabled', 'pricing', 'risk', 'model', 'source', 'code', 'that', 'runs', '300x', 'faster', 'than', 'serial', 'code', 'using', 'new', 'nvidia', 'fermi', 'class', 'tesla', 'series', 'gpu', 'scifinance', 'derivatives', 'pricing', 'and', 'risk', 'model', 'development', 'tool', 'that', 'automatically', 'generates', 'and', 'gpu', 'enabled', 'source', 'code', 'from', 'concise', 'high', 'level', 'model', 'specifications', 'parallel', 'computing', 'cuda', 'programming', 'expertise', 'required', 'scifinance', 'automatic', 'gpu', 'enabled', 'monte', 'carlo', 'pricing', 'model', 'source', 'code', 'generation', 'capabilities', 'have', 'been', 'significantly', 'extended', 'the', 'latest', 'release', 'this', 'includes']
the error rate is:  0.1


In [122]:
reload(bayes)

<module 'bayes' from 'bayes.pyc'>

In [123]:
bayes.spamTest()

porb. of abusive: 0.525
p0V: []
p1V:{}
pSpam
classification error ['yeah', 'ready', 'may', 'not', 'here', 'because', 'jar', 'jar', 'has', 'plane', 'tickets', 'germany', 'for']
the error rate is:  0.1


나이브한 날리즈 레프렌테이션 
* spam mail의 확률
* spam mail일 때 각 단어의 확률

# RSS Feeds

In [148]:
import feedparser

In [131]:
ny = feedparser.parse(
    'https://newyork.craigslist.org/stp/index.rss')

In [132]:
ny

{'bozo': 0,
 'encoding': u'utf-8',
 'entries': [{'dc_source': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
   'dc_type': u'text',
   'id': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
   'language': u'en-us',
   'link': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
   'links': [{'href': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
     'rel': u'alternate',
     'type': u'text/html'}],
   'published': u'2017-09-19T02:56:54-04:00',
   'published_parsed': time.struct_time(tm_year=2017, tm_mon=9, tm_mday=19, tm_hour=6, tm_min=56, tm_sec=54, tm_wday=1, tm_yday=262, tm_isdst=0),
   'rights': u'copyright 2017 craiglist',
   'rights_detail': {'base': u'https://newyork.craigslist.org/search/stp?format=rss',
    'language': None,
    'type': u'text/plain',
    'value': u'copyright 2017 craiglist'},
   'summary': u"average guy s

In [133]:
ny['entries']

[{'dc_source': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
  'dc_type': u'text',
  'id': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
  'language': u'en-us',
  'link': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
  'links': [{'href': u'https://newyork.craigslist.org/brk/stp/d/cool-friend-maybe-more-m4w/6311894226.html',
    'rel': u'alternate',
    'type': u'text/html'}],
  'published': u'2017-09-19T02:56:54-04:00',
  'published_parsed': time.struct_time(tm_year=2017, tm_mon=9, tm_mday=19, tm_hour=6, tm_min=56, tm_sec=54, tm_wday=1, tm_yday=262, tm_isdst=0),
  'rights': u'copyright 2017 craiglist',
  'rights_detail': {'base': u'https://newyork.craigslist.org/search/stp?format=rss',
   'language': None,
   'type': u'text/plain',
   'value': u'copyright 2017 craiglist'},
  'summary': u"average guy seeking a cool female friend that I can chat with laugh bug out

In [135]:
len(ny['entries'])

25

rss feeds를 파싱

In [136]:
ny['entries'][0]['summary']

u"average guy seeking a cool female friend that I can chat with laugh bug out and just be ourselves around each other. Someone who has a good head on a shoulders that's funny mature and cool to hang with it doesnt matter what borough you're from just b ..."

In [137]:
ny['entries'][1]['summary']

u"Looking for Commitment - Let's Get Married!!! \nDon't Spend Another Day as a Single Woman! \nLet's see what we can do about that! \nI'm NOT looking for a one night'er or a fling, but rather a meaningful relationship. \nBased on Openness, Trust and Honest ..."

In [142]:
ny = feedparser.parse(
    'https://newyork.craigslist.org/stp/index.rss')
sf = feedparser.parse(
    'https://sfbay.craigslist.org/stp/index.rss')

In [144]:
vocabList, pSF, pNY = bayes.localWords(ny, sf)

porb. of abusive: 0.533333333333
the error rate is:  0.25


In [141]:
len(ny['entries']), len(sf['entries'])

(25, 25)

In [145]:
vocabList

[u'newbie',
 u'asian',
 u'skin',
 u'alw',
 u'someplace',
 u'buddy',
 u'technique',
 u'young',
 u'send',
 u'charge',
 u'passion',
 u'conversating',
 u'friendly',
 u'brown',
 u'woman',
 u'jerk',
 u'egyptian',
 u'very',
 u'confounding',
 u'every',
 u'bestie',
 u'drinking',
 u'cool',
 u'did',
 u'gender',
 u'accidentally',
 u'standards',
 u'try',
 u'discrete',
 u'race',
 u'small',
 u'enjoy',
 u'says',
 u'hanging',
 u'erotic',
 u'portfolio',
 u'shiatsu',
 u'drinks',
 u'even',
 u'what',
 u'giving',
 u'sun',
 u'while',
 u'lights',
 u'new',
 u'learned',
 u'ever',
 u'told',
 u'full',
 u'shoreline',
 u'exchange',
 u'men',
 u'here',
 u'hours',
 u'shouldn',
 u'let',
 u'sexy',
 u'safer',
 u'great',
 u'kids',
 u'healthy',
 u'wherever',
 u'pics',
 u'social',
 u'existent',
 u'massage',
 u'family',
 u'prefer',
 u'private',
 u'wit',
 u'husbands',
 u'strrings',
 u'use',
 u'takes',
 u'lickking',
 u'two',
 u'37yr',
 u'few',
 u'type',
 u'separated',
 u'females',
 u'relax',
 u'phone',
 u'women',
 u'high',
 u'

In [146]:
len(vocabList)

557

In [149]:
reload(bayes)
bayes.getTopWords(ny, sf)

<module 'bayes' from 'bayes.py'>

porb. of abusive: 0.466666666667
the error rate is:  0.3
SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**SF**
all
love
more
this
doing
got
long
NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**NY**
ever
from
stress
but
will
old
jerk
body
full
give
into
rubdown
size
take
come
week
off
years
guys
like
chat


In [ ]:
re