# Advanced NumPy

In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

In [49]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## ndarray object internals

### NumPy dtype hierarchy

In [2]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [3]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation

### Reshaping arrays

In [4]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C vs. Fortran order

In [10]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and splitting arrays

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [12]:
np.vstack((arr1, arr2))
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [13]:
from numpy.random import randn
arr = randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3])
first
second
third

array([[ 0.1831,  0.2865],
       [-1.3706,  0.2773]])

#### Stacking helpers: 

In [14]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [ 0.7866, -0.1232,  3.    ],
       [-1.2313,  0.5621,  4.    ],
       [-0.5228, -0.9147,  5.    ]])

In [15]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating elements: tile and repeat

In [16]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [17]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [18]:
arr = randn(2, 2)
arr
arr.repeat(2, axis=0)

array([[-0.076 , -0.402 ],
       [-0.076 , -0.402 ],
       [ 1.1028,  0.8102],
       [ 1.1028,  0.8102]])

In [19]:
arr.repeat([2, 3], axis=0)
arr.repeat([2, 3], axis=1)

array([[-0.076 , -0.076 , -0.402 , -0.402 , -0.402 ],
       [ 1.1028,  1.1028,  0.8102,  0.8102,  0.8102]])

In [20]:
arr
np.tile(arr, 2)

array([[-0.076 , -0.402 , -0.076 , -0.402 ],
       [ 1.1028,  0.8102,  1.1028,  0.8102]])

In [21]:
arr
np.tile(arr, (2, 1))
np.tile(arr, (3, 2))

array([[-0.076 , -0.402 , -0.076 , -0.402 ],
       [ 1.1028,  0.8102,  1.1028,  0.8102],
       [-0.076 , -0.402 , -0.076 , -0.402 ],
       [ 1.1028,  0.8102,  1.1028,  0.8102],
       [-0.076 , -0.402 , -0.076 , -0.402 ],
       [ 1.1028,  0.8102,  1.1028,  0.8102]])

### Fancy indexing equivalents: take and put

원소를 지정할 때 정수값으로 지정하는 것, 혹은 리스트로 지정한다. 

In [ ]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

In [ ]:
arr.take(inds)
arr.put(inds, 42)
arr
arr.put(inds, [40, 41, 42, 43])
arr

In [ ]:
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr
arr.take(inds, axis=1)

map은 인자를 함수를 받는다. 함수가 필요한 경우에 put을 사용할 수 있다. 병렬처리가 들어가면서 mapping에서 특정위치의 값을 가져온다고 할 때 사용한다. 

## Broadcasting

https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html

In [22]:
import numpy as np

In [23]:
a = np.array([1.0, 2.0, 3.0]) #1차원

In [24]:
b = np.array([2.0, 2.0, 2.0])

In [25]:
a * b

array([ 2.,  4.,  6.])

In [26]:
b = 2.0 #0차원

In [27]:
a * b

array([ 2.,  4.,  6.])

0차원이 1차원으로 차원을 맞춰주고, 길이를 맞춰주게 된다.<br/>

General Broadcasting Rules
-원소에 대해 두 배열의 형상이 호환되는지 확인
- 끝 차원부터 시작하여 앞으로 짚어감
- ...

In [28]:
x = np.arange(4); x

array([0, 1, 2, 3])

In [31]:
xx = x.reshape(4, 1); xx

array([[0],
       [1],
       [2],
       [3]])

In [32]:
y = np.ones(5); y

array([ 1.,  1.,  1.,  1.,  1.])

In [33]:
z = np.ones((3, 4)); z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [34]:
x.shape

(4,)

In [36]:
y.shape

(5,)

In [38]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [39]:
xx.shape

(4, 1)

In [40]:
y.shape

(5,)

In [41]:
(xx + y).shape

(4, 5)

In [42]:
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [43]:
x.shape

(4,)

In [44]:
z.shape

(3, 4)

In [45]:
(x + z).shape

(3, 4)

In [46]:
x + z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

In [47]:
arr = np.arange(5)
arr
arr * 4

array([ 0,  4,  8, 12, 16])

In [50]:
arr = randn(4, 3)
arr
arr.mean(0)
demeaned = arr - arr.mean(0)
demeaned
demeaned.mean(0)

array([[-0.3146,  1.1774,  0.1966],
       [-1.203 , -0.9236, -0.9688],
       [-0.6102, -0.6438, -0.6699],
       [-1.2259,  1.2241, -0.2294]])

array([-0.8384,  0.2085, -0.4179])

array([[ 0.5238,  0.9689,  0.6145],
       [-0.3645, -1.1322, -0.5509],
       [ 0.2282, -0.8523, -0.2521],
       [-0.3875,  1.0156,  0.1885]])

array([  2.7756e-17,   0.0000e+00,   2.0817e-17])

4*3 와 1*3 <br/>
4->1<br/>
1*3 -> 4* 3<br/>
1에 해당하는 row가 네번 반복

In [51]:
arr
row_means = arr.mean(1)
row_means.reshape((4, 1))
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([[-0.3146,  1.1774,  0.1966],
       [-1.203 , -0.9236, -0.9688],
       [-0.6102, -0.6438, -0.6699],
       [-1.2259,  1.2241, -0.2294]])

array([[ 0.3531],
       [-1.0318],
       [-0.6413],
       [-0.0771]])

array([ -2.7756e-17,  -1.1102e-16,  -3.7007e-17,   1.8504e-17])

### Broadcasting over other axes

In [54]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [55]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.6678,  0.8243, -0.1565],
       [-0.1712,  0.1082,  0.063 ],
       [ 0.0311, -0.0025, -0.0286],
       [-1.1489,  1.3012, -0.1523]])

In [59]:
arr = np.zeros((4, 4))
arr
arr.shape
arr_3d = arr[:, np.newaxis, :]
arr_3d
arr_3d.shape

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

(4, 4)

array([[[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.]]])

(4, 1, 4)

In [64]:
arr_1d = np.random.normal(size=3)
arr_1d
arr_1d[:, np.newaxis]
arr_1d[np.newaxis, :]

array([ 0.2407,  1.6528,  0.3638])

array([[ 0.2407],
       [ 1.6528],
       [ 0.3638]])

array([[ 0.2407,  1.6528,  0.3638]])

In [67]:
arr = randn(3, 4, 5)
arr
depth_means = arr.mean(2)
depth_means
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned
demeaned.mean(2)

array([[[ -3.8643e-01,  -5.1156e-02,  -6.5491e-01,  -1.4536e-01,
          -2.3164e-01],
        [  7.7717e-01,  -5.4282e-01,   1.5107e+00,   1.0218e+00,
           3.1565e-02],
        [ -1.0700e+00,   3.2207e-01,  -1.0930e+00,  -2.8597e-01,
           7.3766e-01],
        [  6.8341e-01,  -1.0941e+00,  -6.5570e-01,  -1.7653e+00,
          -1.0251e+00]],

       [[  7.2358e-01,   1.0266e-01,  -1.3512e+00,   8.4614e-01,
          -1.2523e+00],
        [  2.2306e-03,   7.5725e-01,   2.0326e-01,  -8.5796e-01,
          -6.2280e-01],
        [  4.6092e-01,  -5.1136e-01,  -3.7981e-01,  -9.0222e-01,
          -1.4250e+00],
        [  1.0747e+00,  -1.1692e+00,   1.2412e+00,  -3.0383e-01,
          -1.8796e+00]],

       [[ -1.8033e+00,  -1.6116e-01,   1.1979e-01,   3.6670e-01,
           1.6260e+00],
        [ -9.0288e-01,  -5.2706e-01,   2.3106e+00,  -1.0815e+00,
          -1.3979e+00],
        [  1.3050e+00,  -9.2808e-01,  -7.4094e-01,   8.8685e-01,
           6.2471e-01],
        [ -5.8309

array([[-0.2939,  0.5597, -0.2778, -0.7713],
       [-0.1862, -0.1036, -0.5515, -0.2073],
       [ 0.0296, -0.3197,  0.2295, -0.403 ]])

array([[[-0.0925,  0.2427, -0.361 ,  0.1485,  0.0623],
        [ 0.2175, -1.1025,  0.951 ,  0.4622, -0.5281],
        [-0.7922,  0.5999, -0.8151, -0.0081,  1.0155],
        [ 1.4548, -0.3227,  0.1156, -0.9939, -0.2537]],

       [[ 0.9098,  0.2889, -1.165 ,  1.0323, -1.066 ],
        [ 0.1058,  0.8609,  0.3069, -0.7544, -0.5192],
        [ 1.0124,  0.0401,  0.1717, -0.3507, -0.8735],
        [ 1.282 , -0.9619,  1.4485, -0.0965, -1.6722]],

       [[-1.8329, -0.1908,  0.0902,  0.3371,  1.5964],
        [-0.5831, -0.2073,  2.6304, -0.7618, -1.0781],
        [ 1.0755, -1.1576, -0.9704,  0.6573,  0.3952],
        [-0.1801, -0.4297,  0.1783,  0.4268,  0.0048]]])

array([[ -1.6653e-17,   2.2204e-17,   0.0000e+00,   0.0000e+00],
       [ -8.8818e-17,  -2.2204e-17,  -4.4409e-17,   0.0000e+00],
       [ -4.4409e-17,  -8.8818e-17,   0.0000e+00,  -3.3307e-17]])

arr.mean(2)는 row 한줄에 대한 컴럼들을 더해서 나눈 평균 값~

In [68]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### Setting array values by broadcasting

In [69]:
arr = np.zeros((4, 3))
arr
arr[:] = 5
arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [70]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [71]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [72]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## Advanced ufunc usage

### Ufunc instance methods

In [ ]:
arr = np.arange(10)
np.add.reduce(arr)
arr.sum()

In [ ]:
np.random.seed(12346)

In [ ]:
arr = randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

In [ ]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

In [ ]:
arr = np.arange(3).repeat([1, 2, 2])
arr
np.multiply.outer(arr, np.arange(5))

In [ ]:
result = np.subtract.outer(randn(3, 4), randn(5))
result.shape

In [ ]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

In [ ]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis=1)

### Custom ufuncs

In [ ]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [ ]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [ ]:
arr = randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

## Structured and record arrays

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [ ]:
sarr[0]
sarr[0]['y']

In [ ]:
sarr['x']

### Nested dtypes and multidimensional fields

In [ ]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [ ]:
arr[0]['x']

In [ ]:
arr['x']

In [ ]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

### Why use structured arrays?

### Structured array manipulations: numpy.lib.recfunctions

## More about sorting

In [ ]:
arr = randn(6)
arr.sort()
arr

In [ ]:
arr = randn(3, 5)
arr
arr[:, 0].sort()  # Sort first column values in-place
arr

In [ ]:
arr = randn(5)
arr
np.sort(arr)
arr

In [ ]:
arr = randn(3, 5)
arr
arr.sort(axis=1)
arr

In [ ]:
arr[:, ::-1]

### Indirect sorts: argsort and lexsort

In [ ]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer
values[indexer]

In [ ]:
arr = randn(3, 5)
arr[0] = values
arr
arr[:, arr[0].argsort()]

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

### Alternate sort algorithms

In [ ]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

### numpy.searchsorted: Finding elements in a sorted array

In [ ]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

In [ ]:
arr.searchsorted([0, 8, 11, 16])

In [ ]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side='right')

In [ ]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [ ]:
labels = bins.searchsorted(data)
labels

In [ ]:
Series(data).groupby(labels).mean()

In [ ]:
np.digitize(data, bins)

## NumPy matrix class

In [ ]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:, 0]  # one-dimensional
y = X[:, :1]  # two-dimensional by slicing
X
y

In [ ]:
np.dot(y.T, np.dot(X, y))

In [ ]:
Xm = np.matrix(X)
ym = Xm[:, 0]
Xm
ym
ym.T * Xm * ym

In [ ]:
Xm.I * X

## Advanced array input and output

### Memory-mapped files

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

In [ ]:
section = mmap[:5]

In [ ]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
%xdel mmap
!rm mymmap

### HDF5 and other array storage options

## Performance tips

### The importance of contiguous memory

In [ ]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [ ]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [ ]:
%xdel arr_c
%xdel arr_f
%cd ..

## Other speed options: Cython, f2py, C

```cython
from numpy cimport ndarray, float64_t

def sum_elements(ndarray[float64_t] arr):
    cdef Py_ssize_t i, n = len(arr)
    cdef float64_t result = 0

    for i in range(n):
        result += arr[i]

    return result
```