In [1]:
a = [1, 2, 3]

In [2]:
b = a

In [3]:
a

[1, 2, 3]

In [4]:
b

[1, 2, 3]

In [5]:
a.append(4)

In [6]:
a

[1, 2, 3, 4]

In [7]:
def append_element(some_list, element):
    some_list.append(element)

In [8]:
data = [1, 2, 3]

In [9]:
append_element(data, 7)

In [12]:
a = 5
type(a)

int

In [11]:
a = 'foo'
type(a)
#ctl+shift+-는 셀을 분리한다.

str

In [14]:
a = 4.5
b = 2
print('a is %s, b is %s' % (a, type(b)))
a / b

a is 4.5, b is <class 'int'>


2.25

In [15]:
a = 5
isinstance(a, int)

True

In [16]:
a = 'foo'
a.<tab>

SyntaxError: invalid syntax (<ipython-input-16-e23bc70793b4>, line 2)

In [17]:
getattr(a, 'split')

AttributeError: 'int' object has no attribute 'split'

In [19]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False

In [20]:
isiterable('a string')
isiterable([1, 2, 3])

True

In [23]:
if not isinstance(x, list) and isiterable(x):
    x = list(x)

NameError: name 'x' is not defined

In [24]:
import some_module
result = some_module.f(5)
pi = some_module.PI

In [25]:
print(result, pi)

7 3.13159


In [28]:
from some_module import f, g, PI
result = g(5, PI)

In [29]:
import some_module as sm
from some_module import PI as pi, g as gf

r1 = sm.f(pi)
r2 = gf(6, pi)

In [30]:
a = [1, 2, 3]
b = a
c = list(a)
a is b
a is not c

True

In [31]:
a is not c

True

In [32]:
a ==c

True

In [33]:
a == b

True

In [35]:
a = None
a is None  

True

In [36]:
True & False

False

In [40]:
True ^ False

True

In [39]:
4 & 6

4

In [47]:
##import numpy를 많이 쓴다. 
import numpy as np

from numpy import *
##numpy로부터 모듈을 받아온다. 
##사용에서 차이가 있고, 2번째 방법은 namespace가 오염되는 단점이 있다.

In [44]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
np.array([1, 3, 4])

array([1, 3, 4])

In [46]:
array([1, 3, 4])

array([1, 3, 4])

In [48]:
from numpy import arange

In [50]:
numpy.array([1, 2, 3, 4])
##numpy에서 arange만 import 했기 때문에 error가 난다. 
##특정한 것만 import할 때 

NameError: name 'numpy' is not defined

In [51]:
arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
from pandas import DataFrame, Series
import pandas as pd
##from이 없다면 dataframe이나 series를 쓸때도 pd.datafrme으로 써야하는데
##그것을 쓰기 싫어서 특수한 목적으로 이름을 생략하고 싶을 때 사용한다.
##그외 다른 것은 pd.

# 평가방식

In [57]:
a_list = ['foo', 2, [4, 5]]
a_list[2] = (3, 4)
a_list

['foo', 2, (3, 4)]

In [58]:
a_str = 'hello'
a_str[0] ='m'

TypeError: 'str' object does not support item assignment

In [ ]:
#문자열은 이뮤터블

# scalar Types

### Numeric Type

### string

In [59]:
#여러줄의 문자열을 나타낼때는 """사용한다."""


In [60]:
a = 'this is a string'
a[10] = 'f'

TypeError: 'str' object does not support item assignment

In [61]:
b = a.replace('string', 'longer string')
b

'this is a longer string'

In [62]:
a = 5.6
s = str(a)
s

'5.6'

In [63]:
s = 'python'
list(s)

['p', 'y', 't', 'h', 'o', 'n']

In [64]:
#슬라이싱
s[:3]

'pyt'

In [70]:
list(s[:3])

['p', 'y', 't']

In [69]:
list(s)[:3]

['p', 'y', 't']

In [73]:
#백슬래쉬
s = '12||34'
print(s)

12||34


In [74]:
template = '%.2f %s are worth $%d'

In [75]:
template % (4.5560, 'Argentine Pesos', 1)

'4.56 Argentine Pesos are worth $1'

In [77]:
#float, string, 정수
template % (1210.3, 'Korean Won', 1)

'1210.30 Korean Won are worth $1'

In [79]:
a = [1, 2, 3]
if a: #if 다음은 조건식이 오는데, a 뜻은? > 값이 있느냐 True/ 없느냐 False
    print('I found something!')
    
b = []
if not b:
    print('Empty!')

I found something!
Empty!


In [80]:
#bool의 변환함수
bool([]), bool([1, 2, 3])
bool('Hello world!'), bool('')
bool(0), bool(1)

(False, True)

# Type casting

In [81]:
s = '3.14159'
fval = float(s)

In [82]:
type(fval)

float

In [83]:
int(fval)

3

In [84]:
bool(fval)

True

In [86]:
#문자열로 변환할 때는 str
str(fval)

'3.14159'

# None

In [87]:
#return 값을 안쓰면 none을 반환한다.
a = None
a is None
b = 5
b is not None

True

In [88]:
def add_and_maybe_multiply(a, b, c = None):
    result = a + b
    
    if c is not None:
        result = result * c
        
    return result

# Dates and times

In [89]:
from datetime import datetime, date, time
dt = datetime(2011, 10, 29, 20, 30, 21)
dt.day
dt.minute

30

In [90]:
dt.date()

datetime.date(2011, 10, 29)

In [91]:
dt.time()

datetime.time(20, 30, 21)

In [92]:
dt.minute()

TypeError: 'int' object is not callable

In [93]:
dt.strftime('%m/%d/%Y %H:%M')

'10/29/2011 20:30'

In [94]:
datetime.strptime('20091031', '%Y%m%d')

datetime.datetime(2009, 10, 31, 0, 0)

In [95]:
dt.replace(minute=0, second=0)

datetime.datetime(2011, 10, 29, 20, 0)

In [98]:
dt.replace(minute=0, second=0)
#hour=0, day =1로도 할 수 있다.

datetime.datetime(2011, 10, 29, 20, 0)

In [99]:
#sql로 따지면 인터벌, 빼면 지연된 시간 등을 구할 수 있다.
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 = dt
delta
type(delta)

datetime.datetime

In [ ]:
#dt + 

# if, elif, and else

In [103]:
if x < 0:
    print("It's negetive")

NameError: name 'x' is not defined

In [107]:
#Short-circuit Evalution true or false 이면 true! 
#true가 나오는 순간, 더이상 계산하지 않는다. 
#true와 false일 경우, true계산식을 앞에다 위치시킨다.
#false & True일 경우, false면 뒤에도 false이다. 
a = 5; b = 7

c = 8; d = 4
if a < b or c > d:
    print('Made it')

Made it


# for loop

In [108]:
for value in collection:
    #do someting with value

SyntaxError: unexpected EOF while parsing (<ipython-input-108-6731907709d0>, line 2)

In [110]:
sequence  = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
    if value is None:
        continue
    total += value

In [112]:
sequence = [1, 2, 0, 4 6, 5, 2, 1]
totla_until_5 = 0
for value in sequence:
    if value == 5:
        break
    total_until_5 += value

SyntaxError: invalid syntax (<ipython-input-112-e20cdca2eba6>, line 1)

In [113]:
for a, b, c in iterator:

SyntaxError: unexpected EOF while parsing (<ipython-input-113-382cd3fe351f>, line 1)

In [114]:
#그냥 int값일 경우 error가 나는 것을 볼 수 있다. 
#tuple값으로 설정했을 경우, 여러가지 값을 한번에 받을 수 있다. 
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c, in seq:
    print(a, b, c)

1 2 3
4 5 6
7 8 9


In [ ]:
#x가 0보다 크다면 계속 loop가 돈다. 
#500보다 커지면 나올 수 있다. 
x = 256

# pass

In [ ]:
#틀만 만들어 놓고 아직까진 무엇을 넣어야 할지 모를때 공간만 잡아놓는다. 
if x < 0:
    print 'negative!'
elif x == 0:
    #
    pass
else:
    print'positive!'

In [ ]:
# Exception handling

In [116]:
def attemp_flat(x):
    try:
        return float(x)
    except:
        return x

In [118]:
attempt_float(1.2345)
attempt_float('something')

NameError: name 'attempt_float' is not defined

In [119]:
def attemp_float(x):
    try:
        return float(x)
    except (TypeError, ValueError): #error두가지 이상 튜플로 묶어준다.
        return x

# range 

# Ternary Expressions

In [ ]:
x = 5
value = 'Non'

In [120]:
if x >= 0:
    value = 'Non-negative'
else:
    value = 'Negative'

NameError: name 'x' is not defined

# 튜플

In [121]:
tup = 4, 5, 6
tup

(4, 5, 6)

In [122]:
t1, t2, t3 = 4, 5, 6

In [123]:
print(t1, t2, t3)

4 5 6


In [124]:
#t1은 4 t2는 튜플
t1, t2 = 4, (5, 6)

In [128]:
nestd_tup = (4, 5, 6), (7, 8)
nested_tup

NameError: name 'nested_tup' is not defined

NameError: name 'nested_tup' is not defined

In [129]:
'string' 

'string'

In [131]:
#리스트안에서 항목을 바꾼다는 것은 가능 하지만, 튜플 원소자체를 다른 원소값으로는 바꿀 수 없다. 
#리스트 원소들에 대해서 수정작업은 가능하다. 

tup[1] = [10, 11, 12]

TypeError: 'tuple' object does not support item assignment

In [133]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [134]:
type(('bar'))

str

In [135]:
type(('bar',))

tuple

# 

In [136]:
x = 1, 

In [137]:
x

(1,)

In [138]:
type(x)

tuple

In [139]:
('foo', 'bar' * 4)

('foo', 'barbarbarbar')

In [140]:
#항목이 4번 반복된다. 
(1, 2, 3) * 4

(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)

# Tuple

In [1]:
a = (1, 2, 2, 2, 3, 4, 2)
a.count(2)

4

In [3]:
a.index(2)

1

# List

In [5]:
a_list = [2, 3, 7, None]

tup = ('foo', 'bar', 'baz')
b_list = list(tup)
b_list

['foo', 'bar', 'baz']

In [4]:
b_list[1] = 'peekaboo'
b_list

['foo', 'peekaboo', 'baz']

## Adding and removing elements

In [6]:
b_list.append('dwarf')
b_list

['foo', 'bar', 'baz', 'dwarf']

In [8]:
# 원소를 추가할 수 없다.
b_list[4] = 'big'

IndexError: list assignment index out of range

In [9]:
#순서가 중요하지 않다면 append가 선호된다. 
#append()가 더 빠르기 때문
#하지만 순서를 신경써야 한다면 insert()사용
b_list.insert(1, 'red')
b_list

['foo', 'red', 'bar', 'baz', 'dwarf']

In [13]:
#print에는 여러가지 값을 넣을 수 있다. 
x = b_list.pop(2)
print(b_list, x, sep='\t')

['foo', 'red']	dwarf


In [14]:
b_list.append('foo')
b_list.remove('foo')
b_list

['red', 'foo']

In [15]:
#red가 b_list에 있느냐 
'red' in b_list

True

In [ ]:
#https://docs.python.org/3/ 을 참고하기. 

In [16]:
tup = tuple('string')

In [17]:
tup

('s', 't', 'r', 'i', 'n', 'g')

In [19]:
tup = tuple(['foo', [1, 2], True])

In [20]:
tup[2] = Flase

NameError: name 'Flase' is not defined

In [21]:
tup[1].append(3)

In [22]:
tup

('foo', [1, 2, 3], True)

In [23]:
[4, None, 'foo'] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [24]:
x = [4, None, 'foo']
x.extend([7, 8, (2, 3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

In [26]:
list_of_lists = [[1, 2, 3], [4, None, (3, 2)], 'hello']

In [28]:
everything = []
for chunk in list_of_lists:
    everything.extend(chunk)
#hello는 문자하나하나가 list가 된다.

In [30]:
print(everything)

[1, 2, 3, 4, None, (3, 2), 'h', 'e', 'l', 'l', 'o']


In [31]:
everything = []
for chunk in list_of_lists:
    everything = everything + chunk
#extend()가 속도가 더 빠르다. 

TypeError: can only concatenate list (not "str") to list

In [32]:
#in-place 오퍼레이션 원본 자체를 바꾸는 것 
#https://docs.python.org/3/tutorial/datastructures.html#more-on-lists
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [33]:
a = [7, 2, 5, 1, 3]
a.sort(key=None, reverse = False)
a

[1, 2, 3, 5, 7]

In [35]:
#앞에 글자를 비교
b = ['saw', 'small', 'he', 'foxes', 'six']
b.sort()
b

['foxes', 'he', 'saw', 'six', 'small']

In [36]:
#함수를 넣을 수도 있다. 
b.sort(key=len)
b

['he', 'saw', 'six', 'foxes', 'small']

In [39]:
import bisect
c = [1, 2, 2, 2, 3, 4, 7]
print(bisect.bisect(c, 2))
print(c)
print(bisect.bisect(c, 5))
print(c)
bisect.insort(c, 6)
c

4
[1, 2, 2, 2, 3, 4, 7]
6
[1, 2, 2, 2, 3, 4, 7]


[1, 2, 2, 2, 3, 4, 6, 7]

In [40]:
d = [1, 2, 7, 4, 6, 5]


In [41]:
print(bisect.bisect(d, 3))

2


In [42]:
#따라서, d를 정렬한 후 넣는다. 

In [44]:
d.sort()
print(bisect.bisect(d, 3))
bisect.bisect(d, 3)

2


2

In [45]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]

[2, 3, 7, 5]

In [46]:
seq[3:4] = [6, 3]
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [47]:
#step 간격 1, 3, 5, 7
seq[::2]

[7, 3, 3, 6, 1]

In [52]:
seq[::-1]
#오른쪽에서 왼쪽으로 

[1, 0, 6, 5, 3, 6, 3, 2, 7]

In [48]:
seq[0]

7

In [51]:
seq[-0]

7

## 튜플 복사

In [53]:
#https://docs.python.org/3/library/functions.html
#튜플 복사

In [54]:
t1 = 1, 2, 3

In [55]:
t2 = t1

In [56]:
t1 is t2

True

In [58]:
print(id(t1), id(t2), sep='\t')

80367552	80367552


In [59]:
print(hex(id(t1)), hex(id(t2)), sep='\t')

0x4ca4fc0	0x4ca4fc0


In [60]:
t3 = tuple(t1)

In [62]:
# 주소값은 모두 같다.
print(hex(id(t1)), hex(id(t2)), hex(id(t3)), sep='\t')

0x4ca4fc0	0x4ca4fc0	0x4ca4fc0


## copy module

In [ ]:
#https://docs.python.org/3/library/copy.html

In [61]:
import copy

In [63]:
t4 = copy.copy(t1); t5 = copy.deepcopy(t1)

In [64]:
print(hex(id(t1)), hex(id(t4)),  hex(id(t4)), sep='\t')

0x4ca4fc0	0x4ca4fc0	0x4ca4fc0


In [ ]:
#튜플은 복제가 안된다. 

# 2. 리트스 복제

In [65]:
l1 = [1, 2, 3, 4]

In [66]:
l2 = l1

In [67]:
# 같은 곳을 가리킬까? 주소값을 복제하는 것이기 때문에 

In [68]:
print(hex(id(l1)), hex(id(l2)), sep='\t')

0x4d334c8	0x4d334c8


In [69]:
l3 = list(range(5)); l3

[0, 1, 2, 3, 4]

In [70]:
l3 = list(range(1, 5)); l3

[1, 2, 3, 4]

In [71]:
#이터레이터
range(1, 5)

range(1, 5)

In [73]:
print(hex(id(l1)), hex(id(l2)), hex(id(l3)), sep='\t')

0x4d334c8	0x4d334c8	0x4d4ba88


In [74]:
l4 = list(l1)

In [75]:
print(hex(id(l1)), hex(id(l2)), hex(id(l4)), sep='\t')

0x4d334c8	0x4d334c8	0x4d55388


In [76]:
l5 = copy.copy(l1)
l6 = copy.deepcopy(l1)

In [78]:
print(hex(id(l1)), hex(id(l5)), hex(id(l6)), sep='\t')
#리스트에 대한 복제는 실제로 복제가 일어난다.

0x4d334c8	0x3a50248	0x4c90248


# 3.shallow copy VS deep copy

In [80]:
# shallow
# deep은 list안에 list도 copy

In [81]:
c = [1, 2, [3, 4, 'hello'], 10]

In [82]:
x = 1

In [83]:
print(hex(id(x)), hex(id(c[0])), sep='\t')

0x595be9d0	0x595be9d0


In [84]:
x = 2
y = [1, 2, 3]

In [85]:
print(hex(id(x)), hex(id(y)), hex(id(y[0])), hex(id(y[2])), sep='\t')

0x595be9f0	0x4d29308	0x595be9d0	0x595bea10


In [86]:
c1 = list(c)
c2 = copy.copy(c)
c3 = copy.deepcopy(c)

In [87]:
c

[1, 2, [3, 4, 'hello'], 10]

In [88]:
c1 == c

True

In [89]:
c2 ==c

True

In [90]:
c3 == c

True

In [91]:
#값은 다 똑같다

In [92]:
c1 is c

False

In [93]:
c2 is c

False

In [94]:
c3 is c

False

In [95]:
c

[1, 2, [3, 4, 'hello'], 10]

In [96]:
print(hex(id(c[1])), hex(id(c1[1])), hex(id(c2[1])), hex(id(c3[1])), sep='\t')

0x595be9f0	0x595be9f0	0x595be9f0	0x595be9f0


### 리스트 내의 리스트는 복제되었을까? 참조되었을까?

In [97]:
print(hex(id(c[2])), hex(id(c1[2])), hex(id(c2[2])), hex(id(c3[2])), sep='\t')

0x4d29208	0x4d29208	0x4d29208	0x4d55248


In [100]:
z = [[8, [9]], 5]
z1 = z
z2 = list(z)
z3 = copy.deepcopy(z)

In [101]:
print(hex(id(z)), hex(id(z1)), hex(id(z2)), hex(id(z3)), sep='\t')

0x4c90a48	0x4c90a48	0x4d5a648	0x4d5a248


In [102]:
#z의 원소개수는
len(z)

2

In [103]:
c1, c2, c3 = 8, 9, 5

In [105]:
print(id(c3), id(z[1]), id(z[1]), id(z2[1]), id(z3[1]), sep='\t')

1499195984	1499195984	1499195984	1499195984	1499195984


In [106]:
print(id(z), id(z1), id(z2), id(z3), sep='\t')

80284232	80284232	81110600	81109576


In [107]:
print(id(z[0]), id(z2[0]), id(z3[0]), sep='\t')

81089992	81089992	81109384


In [108]:
z[0][0]

8

# enumerate

In [109]:
some_list = ['foo', 'bar', 'baz']
for item in (some_list):
    print(item)

foo
bar
baz


In [111]:
some_list = ['foo', 'bar', 'baz']
for index, item in enumerate(some_list):
    print(index, item)

0 foo
1 bar
2 baz


In [112]:
mapping = dict((v, i) for i, v in enumerate(some_list))
mapping

{'bar': 1, 'baz': 2, 'foo': 0}

# sorted

In [113]:
x = [7, 1, 2, 6, 0, 3, 2]
x.sort()
x

[0, 1, 2, 2, 3, 6, 7]

In [116]:
y = sorted(x)

In [119]:
x is y

False

In [118]:
print(x, y)
#값은 같은데 , 다른 메모리 공간을 차지하고 있다. 

[0, 1, 2, 2, 3, 6, 7] [0, 1, 2, 2, 3, 6, 7]


In [121]:
a = [1, 3, 6, 4, 2]
b = sorted(a)

In [122]:
print(a, b)

[1, 3, 6, 4, 2] [1, 2, 3, 4, 6]


In [123]:
# 순서가 다른데 같다고 할까? 순서가 다르면 리스트는 다르다.

In [124]:
print(a is b, a==b)

False False


In [125]:
#구성요소가 같다면 같다고 표현하고 싶다. 그럴땐 집합이 쓰여진다. 

In [126]:
print(a is b, set(a) == set(b))

False True


In [128]:
#set은 순서는 상관없다. 구성요소가 같다고 하면, 같다고 본다.
#순서가 없고 중복을 허용하지 않는다.

In [129]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [132]:
set(sorted('horse race'))
#집합은 중복을 허용하지 않는다.
#중복되는 값이 있으면 하나만 

{' ', 'a', 'c', 'e', 'h', 'o', 'r', 's'}

In [131]:
sorted(set('this is jus some string'))

[' ', 'e', 'g', 'h', 'i', 'j', 'm', 'n', 'o', 'r', 's', 't', 'u']

In [115]:
sorted([7, 1, 2, 6, 0, 3, 2])

[0, 1, 2, 2, 3, 6, 7]

In [114]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [ ]:
#정렬하고 집합, 집합하고 정렬
#갯수를 줄이고 정렬하는 것이 빠르다. 

# zip

In [134]:
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
list(zip(seq1, seq2))

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [135]:
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
z =zip(seq1, seq2)

In [137]:
for val in list(z):
    print(val)

('foo', 'one')
('bar', 'two')
('baz', 'three')


In [ ]:
for i, (a, b) in enumerae(z)

In [150]:
pitchers = [('Nolan', 'Ryan'), ('Roger', "Clememes"), ('Schilling', 'Curt')]

In [140]:
first_names, last_names = zip(*pitchers)
print(first_names)
print(last_names)

('Nolan', 'Roger', 'Schilling')
('Ryan', 'Clememes', 'Curt')


In [142]:
[first_names,last_names]
man

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clememes', 'Curt')]

In [143]:
list(zip(*man))

[('Nolan', 'Ryan'), ('Roger', 'Clememes'), ('Schilling', 'Curt')]

In [145]:
a = [1, 2, 3, 4]

In [146]:
zip(a, a)

In [148]:
#첫번째 배열끼리, 두번째 배열끼리 묶인다. 
list(zip(a, a))

[(1, 1), (2, 2), (3, 3), (4, 4)]

In [149]:
list(zip(a, a, a))

[(1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 4)]

In [151]:
pitchers

[('Nolan', 'Ryan'), ('Roger', 'Clememes'), ('Schilling', 'Curt')]

In [152]:
#position argument로 풀려서 들어간다. 
#argument의 갯수가 가변 항목으로 되어있다. 
list(zip(*pitchers))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clememes', 'Curt')]

In [153]:
list(zip(*pitchers))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clememes', 'Curt')]

In [155]:
list(zip(pitchers[0], pitchers[1], pitchers[2]))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clememes', 'Curt')]

In [157]:
zip(('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt'))

In [158]:
list(zip(('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clemens', 'Curt')]

In [159]:
p1, p2, p3 = ('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')

In [160]:
list(zip(p1, p2, p3))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clemens', 'Curt')]

In [163]:
p = (p1, p2, p3)
p

(('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt'))

In [165]:
list(zip(*p))

[('Nolan', 'Roger', 'Schilling'), ('Ryan', 'Clemens', 'Curt')]

In [166]:
#https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions

In [167]:
#https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/

In [171]:
def test_var_args(f_arg, *argv):
    print("first normal arg:", f_arg)
    for arg in argv:
        print("another arg through *argv :", arg)

In [172]:
test_var_args(10)

first normal arg: 10


In [173]:
test_var_args(10, 11, 12, 13)

first normal arg: 10
another arg through *argv : 11
another arg through *argv : 12
another arg through *argv : 13


In [176]:
#이름은 크게 문제는 없지만 약속은 argv

#임의의 인자를 받는 별표를 쓸 때에는 반드시 받는 아규먼트를 머저 정의해주고 
#나중에! 

In [186]:
def greet_me(**kwargs):
    if kwargs is not None:
        print (kwargs.keys())
        for key in kwargs.keys():
            print("%s == %s" %(key, kwargs[key]))

In [187]:
greet_me(a='HELLO', b='world', name='python')

dict_keys(['a', 'b', 'name'])
a == HELLO
b == world
name == python


In [191]:
kwargs = {'a': 'hello', 'b':'world', 'name':'python'}

In [192]:
kwargs['a']

'hello'

In [193]:
d = {'a': 'hello', 'b':'world', 'name':'python'}

In [194]:
greet_me(**d)

dict_keys(['a', 'b', 'name'])
a == hello
b == world
name == python


# 고정 아규먼트, 키워드 아규먼트 

## Dict

In [195]:
empty_dict = []
d1 = {'a': 'some value', 'b': [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [196]:
d1[7] = 'an integer'
d1
d1['b']

[1, 2, 3, 4]

In [197]:
#key가 있는지 확인 가능 
'b' in d1

True

In [198]:
#dic의 value값은 확인 간으할까? no

In [199]:
d1[5] = 'some value'
d1['dummy'] = 'another value'
del d1[5]
ret = d1.pop('dummy')
ret

'another value'

In [200]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [204]:
d1.keys()
list(d1.keys())

['a', 'b', 7, 'c']

In [202]:
d1.values()

dict_values(['some value', [1, 2, 3, 4], 'an integer'])

In [207]:
#다른 사전과 결합시킬때 ! but 같은 키가 있을 때는
#b key가 유니크 하지 않으니까 update 된다.
d1.update({'b':'foo', 'c':12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

In [206]:
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

# creating dicts from sequences

### List, set, and dict comprehensions

In [209]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']
strings

['a', 'as', 'bat', 'car', 'dove', 'python']

In [ ]:
#[expr for val in iterable if condition else expr]
#iterable의 있는 값이 val로 넘어가서 조건을 만족/불만족

In [211]:
#리스트 내포!!
[x.upper() for x in strings if len(x) > 2]
#for니까 값이 하나씩 넘어온다. 

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [212]:
result = []
for x in strings:
    if len(x) > 2:
        result.append(x.upper())
result
#append때문에 오버헤드가 발생

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [213]:
result = []
for x in strings:
    if len(x) > 2:
        result.append(x.upper())
        print(result)
result
#print를 확인하려면 append를 사용해야 한다. 

['BAT']
['BAT', 'CAR']
['BAT', 'CAR', 'DOVE']
['BAT', 'CAR', 'DOVE', 'PYTHON']


['BAT', 'CAR', 'DOVE', 'PYTHON']

In [215]:
#중복을 제거하고 싶을 때 set로 만든다.
lengths = [len(x) for x in strings]
lengths

[1, 2, 3, 3, 4, 6]

In [214]:
unique_lengths = [len(x) for x in strings]
unique_lengths

[1, 2, 3, 3, 4, 6]

In [217]:
loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [216]:
#물론 index:val의 순서를 바꾸어도 된다. 
loc_mapping = {index : val for index, val in enumerate(strings)}
loc_mapping

{0: 'a', 1: 'as', 2: 'bat', 3: 'car', 4: 'dove', 5: 'python'}

In [220]:
loc_mapping = dict((val, idx) for idx, val in enumerate(strings))

#### Nested list comprehensions

In [221]:
all_data = [['Tom', 'Billy', 'Jefferson', 'Andrew', 'Wesley', 'Steven', 'Joe'],
            ['Susie', 'Casey', 'Jill', 'Ana', 'Eva', 'Jennifer', 'Stephanie']]

In [223]:
names_of_interest = []
# for name의  name에 각 원소가 대입되서 if문 비교가 진행된다.
# 두번째 리스트에 있는, in names names로 대입된다.
for names is all_data:
    enough_es = [name for name in names if name.count('e') >= 2]
    names_of_interest.extend(enough_es)
names_of_interest

SyntaxError: invalid syntax (<ipython-input-223-0621303a8c16>, line 4)

In [224]:
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count('e') > 2]
    names_of_interest.extend(enough_es)
names_of_interest    

[]

In [225]:
#중첩 for를 리스트내포를 써서 바깥안쪽 for문을 리스트 컴프리핸션?을 쓸 수 있다. 
result = [name for names in all_data for name in names 
          if name.count('e') >= 2]
result
#위에 for문을 첫번째, 안에 for문을 이어서! 

['Jefferson', 'Wesley', 'Steven', 'Jennifer', 'Stephanie']

In [226]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
some_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]
flattened = [x for tup in some_tuples for x in tup]
flattened

In [227]:
flattened = []

for tup in some_tuples:
    for x in tup:
        flattened.append(x)

In [232]:
In [229]: [[x for x in tup] for tup in some_tuples]
#리스트에 리스트가 만들어진다.
#튜플의 리스트를 리스트의 리스트로 변환해준다.

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [230]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [235]:
def scope_test():
    def do_local():
        spam ="local spam"
    def do_nonlocal():
        nonlocal spam
        spam = "nonlocal spam"
    def do_global():
        global spam
        spam = "global spam"
        
    spam = "test spam"
    do_local()
    print("After local assignment", spam)
    do_nonlocal()
    print("After nonlocal assignment", spam)
    do_global()
    print("After global assignment", spam)
scope_test()
print("In global scope", spam)

After local assignment test spam
After nonlocal assignment nonlocal spam
After global assignment nonlocal spam
In global scope global spam


In [236]:
def func():
    a = []
    for i in range(5):
        a.append(i)

In [237]:
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c
a, b, c = f()

In [239]:
print(a, b, c)

5 6 7


In [240]:
return_value = f()
return_value

(5, 6, 7)

In [241]:
def f():
    a = 5
    b = 6
    c = 7
    return {'a' : a, 'b' : b, 'c' : c}

In [242]:
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']

In [243]:
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]', '', value)
        value = value.title()
        result.append(value)
    return result

In [244]:
In [15]: clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [ ]:
def remove_punctuation(value):
    return re.sub

In [247]:
def remove_punctuation(value):
    return re.sub('[!#?]', '', value)

clean_ops = [str.strip, remove_punctuation, str.lower]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

In [248]:
In [22]: clean_strings(states)

NameError: name 'ops' is not defined

In [ ]:
# 일종의 레이지 ..evalulation