# # Getting Started with Numpy
### <p style="color:Tomato">Learn the basics of Numpy while working with alcohol consumption data<p/>

#### <p style="color:Gray">world_alcohol.csv<p/>
: Which records per capita alcohol consumption for each country.<br/>
각 국가별로 1인당 알코올 섭취량을 기록
* a comma separated value dataset
* specify the delimiter using the delimiter parameter

<p style="color:Blue">**1. Which records per capita alcohol consumption for each country.**<p/>

> learning of the basics of the NumPy library and how to work with NumPy arrays. 

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
import numpy as np

In [3]:
vector = np.array([5, 10, 15, 20])
vector
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([ 5, 10, 15, 20])

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
vector = np.array([10, 20, 30])
vector
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

array([10, 20, 30])

#### <p style="color:Gray">ndarray.shape<p/><hr>
To figure out how many elements are in the array.

In [5]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)

(4,)


> This tuple indicates that the array vector has one dimension, with length 4, which matches our intuition that vector has 4 elements.

In [6]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(2, 3)


> The above code will result in the tuple (2,3) indicating that matrix has 2 rows and 3 columns.

In [7]:
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(4,)
(2, 3)


#### <p style="color:Gray">numpy.genfromtxt()<p/><hr>
Read in datasets.<br/>


In [8]:
nfl = np.genfromtxt("nfl.csv", delimiter=",")
print(nfl[:10])

[[             nan              nan              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]
 [  2.00900000e+03   1.00000000e+00              nan              nan]]


In [9]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter=",")
print(type(world_alcohol))
print(world_alcohol[:10])

<class 'numpy.ndarray'>
[[             nan              nan              nan              nan
               nan]
 [  1.98600000e+03              nan              nan              nan
    0.00000000e+00]
 [  1.98600000e+03              nan              nan              nan
    5.00000000e-01]
 [  1.98500000e+03              nan              nan              nan
    1.62000000e+00]
 [  1.98600000e+03              nan              nan              nan
    4.27000000e+00]
 [  1.98700000e+03              nan              nan              nan
    1.98000000e+00]
 [  1.98700000e+03              nan              nan              nan
    0.00000000e+00]
 [  1.98700000e+03              nan              nan              nan
    1.30000000e-01]
 [  1.98500000e+03              nan              nan              nan
    3.90000000e-01]
 [  1.98600000e+03              nan              nan              nan
    1.55000000e+00]]


#### <p style="color:Gray">dtype<p/><hr>
Numpy will automatically figure out an appropriate data type when reading in data of converting lists to arrays. Check the data type of a Numpy array<br/>

NumPy는 데이터를 읽거나 목록을 배열로 변환 할 때 자동으로 적절한 데이터 유형을 찾습니다. dtype 속성을 사용하여 NumPy 배열의 데이터 유형을 확인할 수 있습니다.

In [10]:
numbers = np.array([1, 2, 3, 4])
numbers.dtype

dtype('int32')

In [11]:
world_alcohol_dtype = world_alcohol.dtype
world_alcohol_dtype

dtype('float64')

### <p style="color:Tomato">How to deal with missing data<p/>
#### <p style="color:Gray">Nan<p/><hr>
Which stands for "Not a number", is a data type used to represent missing values.<br/>
NumPy can't convert a value to a numeric data type like float or integer, it uses a special nan value that stands for "not a number".<br/>
When NumPy can't convert a value to a numeric data type like float or integer, it uses a special nan value that stands for "not a number".
* header
#### <p style="color:Gray">skip_header<p/><hr>
> To skep the header when reading in the data, we use the skip_header parameter. The skip_header parameter accepts an integer value, specifying the number of lines from the top of the file we want Numpy to ignore. 

<br/>


* To specify the data type for the entire Numpy array, we use the keyword argument dtype and set it to "U75".
* This specifies that we want to read in each value as a 75 byte unicode data type.


In [12]:
world_alcohol = np.genfromtxt(
    'world_alcohol.csv', 
    dtype='U75', 
    delimiter=',',
    skip_header=1)

In [13]:
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


#### <p style="color:Gray">Indexing Array<p/><hr>

In [14]:
vector = np.array([5, 10, 15, 20])
print(vector[0])

5


In [15]:
list_of_lists = [[5, 10, 15], [20, 25, 30]]

In [16]:
first_item = list_of_lists[0]
first_item
first_item[2]

list_of_lists[0][2]

[5, 10, 15]

15

15

In [17]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
matrix[1, 2]

30

In [18]:
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

In [19]:
world_alcohol = np.genfromtxt(
    'world_alcohol.csv', 
    dtype='U75', 
    delimiter=',')
world_alcohol

array([['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ..., 
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

In [20]:
world_alcohol = np.genfromtxt(
    'world_alcohol.csv', 
    dtype='U75', 
    delimiter=',',
    skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

In [21]:
# uruguay_other_1986 = world_alcohol[1][4]
uruguay_other_1986 = world_alcohol[1, 4]
uruguay_other_1986

'0.5'

In [22]:
# third_country = world_alcohol[2][2]
third_country = world_alcohol[2, 2]
third_country

"Cte d'Ivoire"

#### <p style="color:Gray">Slicing Array<p/><hr>
> The colon by itself : specifies that the entirety of a single dimension should be selected.

In [23]:
vector = np.array([5, 10, 15, 20])
vector[0:3]

array([ 5, 10, 15])

In [24]:
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])

In [25]:
matrix[:, 1]

array([10, 25, 40])

In [26]:
countries = world_alcohol[:, 2]
countries

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], 
      dtype='<U75')

In [27]:
alcohol_consumption = world_alcohol[:, 4]
alcohol_consumption

array(['0', '0.5', '1.62', ..., '2.54', '0', '5.15'], 
      dtype='<U75')

#### <p style="color:Gray">Slicing One dimention<p/><hr>
To select one whole dimension, and a slice of the other, we need to use special notation

In [28]:
matrix = np.array([
                    [5, 10, 15], 
                    [20, 25, 30],
                    [35, 40, 45]
                 ])

In [29]:
matrix[:, 0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [30]:
matrix[1:3, :]

array([[20, 25, 30],
       [35, 40, 45]])

In [31]:
matrix[1:3, 1]

array([25, 40])

In [32]:
first_two_columns = world_alcohol[:, 0:2]
first_two_columns

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ..., 
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], 
      dtype='<U75')

In [33]:
first_ten_years = world_alcohol[0:10, 0]
first_ten_years

array(['1986', '1986', '1985', '1986', '1987', '1987', '1987', '1985',
       '1986', '1984'], 
      dtype='<U75')

In [34]:
first_ten_rows = world_alcohol[0:10, :]
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], 
      dtype='<U75')

#### <p style="color:Gray">Slicing arrays<p/><hr>
slice along both dimensions simultaneously.

In [35]:
matrix[1:3, 0:2]

array([[20, 25],
       [35, 40]])

In [36]:
first_twenty_regions = world_alcohol[0:20, 1:3]
first_twenty_regions

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], 
      dtype='<U75')

#### <p style="color:Gray">world_alcohol.csv<p/>
<p style="color:Blue">**2. Each row specifies how many liters of a type of alcohol the average citizen of a particular country drank in a given year.** <p/>
For example, One row shows **how many liters of wine the typical Vietnamese citizen drank in 1986.**<br/>
각 행은 특정 국가의 시민들이 주어진 해에 특정종류의 알콜을 얼마나 마셨는지 나타냅니다. 예를 들어, 베트남 시민이 1986년에 마신 와인의 양은 얼마인가를 보여줍니다. 

> * Year -- The year the data in the row is for
* WHO Region -- The region in which the country is located
* Country -- The country of the data is for
* Beverage Types -- The type of beverage
* Display Value -- The average number of liters drunk per capita

### <p style="color:Tomato">Computation with NumPy<p/>
#### <p style="color:Gray">Array Comparisons<p/><hr>
The NumPy modules is the ability to make comparisons across an entire array. These comparisons result in **Boolean Values**


In [37]:
vector = np.array([5, 10, 15, 20])
vector == 10

array([False,  True, False, False], dtype=bool)

In [38]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [39]:
countries_canada = world_alcohol[:, 2] == 'Canada'
countries_canada

array([False, False, False, ..., False, False, False], dtype=bool)

In [40]:
years_1984 = world_alcohol[:, 0] == '1984'
years_1984 

array([False, False, False, ..., False, False, False], dtype=bool)

#### <p style="color:Gray">Selecting Elements<p/><hr>
Select certain elements in vectors, or certain rows in matrics.

In [41]:
vector

array([ 5, 10, 15, 20])

In [42]:
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])

[10]


In [43]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
second_column_25 = (matrix[:, 1] == 25)
print(matrix[second_column_25, :])

[[20 25 30]]


In [45]:
country_is_algeria = world_alcohol[:, 2] == 'Algeria'
contry_algeria = world_alcohol[country_is_algeria, :]
country_is_algeria
contry_algeria

array([False, False, False, ..., False, False, False], dtype=bool)

array([['1984', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1987', 'Africa', 'Algeria', 'Beer', '0.17'],
       ['1987', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1984', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Beer', '0.16'],
       ['1989', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1989', 'Africa', 'Algeria', 'Wine', '0.23'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1984', 'Africa', 'Algeria', 'Wine', '0.12'],
       ['1985', 'Africa', 'Algeria', 'Beer', '0.19'],
       ['1985', 'Africa', 'Algeria', 'Other', '0'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1985', 'Africa', 'Algeria', 'Wine', '0.11'],
       ['1986', 'Africa', 'Algeria', 'Other', '0'],
       ['1989', 'Africa', 'Algeria', 'Other', '0'],
       ['1987', 'Africa', 'Algeria', 'Other', '0'],
       ['1984', 'Africa', 'Algeria', 'Beer', '0.2'],
       ['1985', 'Africa', 'A

#### <p style="color:Gray">Comparisons with Multiple Conditions<p/><hr>
We can also perform comparisons with multiple conditions by specifying each one separately, then joining the with an ampersand(&).

In [46]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
equal_to_ten_and_five
#  none of the elements can be 10 and 5 at the same time

array([False, False, False, False], dtype=bool)

In [47]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
equal_to_ten_or_five

array([ True,  True, False, False], dtype=bool)

In [48]:
is_algeria_and_1986 =( 
                    world_alcohol[:, 0] == '1986') & (
                    world_alcohol[:, 2] == 'Algeria')

In [49]:
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986, :]
rows_with_algeria_and_1986

array([['1986', 'Africa', 'Algeria', 'Wine', '0.1'],
       ['1986', 'Africa', 'Algeria', 'Spirits', '0.01'],
       ['1986', 'Africa', 'Algeria', 'Beer', '0.18'],
       ['1986', 'Africa', 'Algeria', 'Other', '0']], 
      dtype='<U75')

#### <p style="color:Gray">Replacing Values<p/><hr>
Use comparisons to replace values in an array based on certain conditions.

In [50]:
vector = np.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
equal_to_ten_or_five
vector[equal_to_ten_or_five]
vector[equal_to_ten_or_five] = 50
print(vector)

array([ True,  True, False, False], dtype=bool)

array([ 5, 10])

[50 50 15 20]


In [51]:
matrix = np.array([
         [5, 10, 15], 
         [20, 25, 30],
         [35, 40, 45]
        ])

In [52]:
second_column_25 = matrix[:, 1] == 25
matrix[second_column_25, 1] = 10
matrix

array([[ 5, 10, 15],
       [20, 10, 30],
       [35, 40, 45]])

<p style="color:Blue">**3. Replace all instance of the string 1986 in the first column of world_alcohol with the string 2014.** <p/>

In [53]:
world_alcohol[:, 0][world_alcohol[:, 0] == '1986'] = '2014'

In [54]:
world_alcohol

array([['2014', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['2014', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['2014', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2014', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

In [55]:
world_alcohol[:, 3][world_alcohol[:, 3] == 'Wine'] = 'Grog'
world_alcohol

array([['2014', 'Western Pacific', 'Viet Nam', 'Grog', '0'],
       ['2014', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Grog', '1.62'],
       ..., 
       ['2014', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['2014', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

#### <p style="color:Gray">Replacing Empty Strings<p/><hr>
**The Display Value column**:<br/>

Which shows how much alcohol the average citizen of a country drinks.<br/>
* world_alcohol currently has a unicode datatype, all of the values in the column are strings.
* So we can't to add these values together or perform any other mathematical operations on them, we'll have to convert the data in the column to floats.
* We need to address the empty string values (") that appear where there was *no original data* for the given *country* and *year*. If we try to convert the data in the column to floats without removing these values first, we'll get a ValueError.

<br/>
이 칼럼은 한 국가의 평균 시민이 마시는 알코올 섭취량을 보여줍니다.
* world_alcohol에는 유니코드 데이터를 가지고 있고, 모든 컬럼의 값은 문자열이다. 
* 이 값을 더하거나 다른 수학 연산을 수행하려면 열의 데이터를 float로 변환해야합니다. 
* 데이터가 없는 국가 및 연도 칼럼의 빈 문자열을 처리해야 합니다. 이 값을 먼저 제거하지 않고 열의 데이터를 부동으로 변환하려고 하면 ValueError가 표시됩니다.  

In [56]:
world_alcohol = np.genfromtxt(
    'world_alcohol.csv', 
    dtype='U75', 
    delimiter=',',
    skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

In [57]:
is_value_empty = world_alcohol[:, 4] == ''
is_value_empty

array([False, False, False, ..., False, False, False], dtype=bool)

In [58]:
world_alcohol[is_value_empty, 4] = '0'
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ..., 
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], 
      dtype='<U75')

#### <p style="color:Gray">Converting Data Types<p/><hr/>
#### <p style="color:Gray"># astype()<p/>

In [59]:
vector = np.array(["1", "2", "3"])
print(type(vector))

vector = vector.astype(float)
vector

<class 'numpy.ndarray'>


array([ 1.,  2.,  3.])

<p style="color:Blue">**4. Figure out detemine which country drinks the most.** <p/>

In [60]:
alcohol_consumption = world_alcohol[:, 4].astype(float)
print(alcohol_consumption)

[ 0.    0.5   1.62 ...,  2.54  0.    5.15]


#### <p style="color:Gray">sum(), mean(), max() with vector<p/>

In [61]:
vector = np.array([5, 10, 15, 20])
vector.sum()

50

#### <p style="color:Gray">sum(), mean(), max() with matrix<p/>
**axis** <br/>
We have to specify an additional keyword argument, axis
* 1 means that we want to perform the operation on each row
* 0 means on each column


In [62]:
matrix = np.array([
            [5, 10, 15],
            [20, 25, 30],
            [35, 40, 45]
            ]) 
matrix.sum(axis=1)

array([ 30,  75, 120])

In [63]:
alcohol_consumption.dtype

dtype('float64')

In [64]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()
total_alcohol
average_alcohol

3908.96

1.2001719373656738

<p style="color:Blue">**5. To find the total amount the average person in Canada drank in 1986.** <p/>
Each country is associated with several rows for different types of beverages:<br/>
For example, we'd have to add up all 4 of the rows shown above, then repeat this process for each country.

In [67]:
is_canada_1986 = (world_alcohol[:, 2] == 'Canada') & (
                  world_alcohol[:, 0] == '1986')

In [68]:
canada_1986 = world_alcohol[is_canada_1986, :]

In [69]:
canada_alcohol = canada_1986[:, 4]

In [70]:
empty_strings = canada_alcohol == ''

In [71]:
canada_alcohol[empty_strings] = "0"

In [72]:
canada_alcohol = canada_alcohol.astype(float)

In [73]:
total_candian_drinking = canada_alcohol.sum()
total_candian_drinking

9.3100000000000005

#### <p style="color:Gray">Calculating Consumption for Each Country<p/><hr/>
<p style="color:Blue">**6. Scale up the process and make the same calculation for all countries in a given year.** <p/>
* Computed total alcohol consumption for each country in 1989.

In [74]:
totals = {}
is_year = world_alcohol[:, 0] == "1989"
year = world_alcohol[is_year, :]

In [77]:
countries
year

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], 
      dtype='<U75')

array([['1989', 'Americas', 'Guatemala', 'Beer', '0.62'],
       ['1989', 'Africa', 'Seychelles', 'Beer', '2.23'],
       ['1989', 'Americas', 'Costa Rica', 'Spirits', '4.51'],
       ..., 
       ['1989', 'Eastern Mediterranean', 'Morocco', 'Spirits', '0.07'],
       ['1989', 'Europe', 'Poland', 'Beer', '2.03'],
       ['1989', 'Europe', 'Turkey', 'Other', '0']], 
      dtype='<U75')

In [78]:
# ['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value']
for country in countries:
    is_country = year[:, 2] == country
    country_consumption = year[is_country, :]
    alcohol_column = country_consumption[:, 4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()

In [79]:
totals

{'Afghanistan': 0.0,
 'Albania': 1.73,
 'Algeria': 0.40000000000000002,
 'Angola': 2.2799999999999998,
 'Antigua and Barbuda': 4.6900000000000004,
 'Argentina': 10.82,
 'Australia': 12.09,
 'Austria': 13.9,
 'Bahamas': 12.290000000000001,
 'Bahrain': 4.8899999999999997,
 'Bangladesh': 0.0,
 'Belarus': 7.9799999999999995,
 'Belgium': 11.609999999999999,
 'Belize': 0.0,
 'Benin': 1.3800000000000001,
 'Bhutan': 0.31,
 'Bolivia (Plurinational State of)': 3.0499999999999998,
 'Botswana': 4.6299999999999999,
 'Brazil': 5.5199999999999996,
 'Brunei Darussalam': 2.7800000000000002,
 'Bulgaria': 11.43,
 'Burkina Faso': 3.9900000000000002,
 'Burundi': 8.1599999999999984,
 'Cabo Verde': 2.79,
 'Cambodia': 0.33000000000000002,
 'Cameroon': 6.3599999999999994,
 'Canada': 9.0,
 'Central African Republic': 2.5199999999999996,
 'Chad': 0.30000000000000004,
 'Chile': 8.6499999999999986,
 'China': 3.3300000000000001,
 'Colombia': 6.9600000000000009,
 'Comoros': 0.10999999999999999,
 'Congo': 3.150000000

<p style="color:Blue">**7. Loop through the totals dictionary to find the country the country with the highest value.** <p/>
Dictionary에서 가장 가치가 높은 국가를 찾습니다.

In [80]:
highest_value = 0
highest_key = None
for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country   

In [81]:
highest_key

'Hungary'